# -*- mode: ruby -*-
# vi: set ft=ruby :

PROJECT = "booksite_search"
FOLDER = "../develop"
VAGRAT = "/vagrant"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "#{PROJECT}" do |project|

    project.vm.box = "centos/7"

  	# Port forward 80 to 8080
  	project.vm.network "forwarded_port", guest: 80, host: 8080
    project.vm.network "private_network", ip: "192.168.100.50"
    project.vm.synced_folder "#{FOLDER}", "#{VAGRAT}", type:"nfs"
    
    project.vm.provision :shell, :path => "bootstrap/mount-webroot.sh"
    project.vm.provision :shell, :path => "bootstrap/apache.sh"
    project.vm.provision :shell, :path => "bootstrap/epel.sh"
    project.vm.provision :shell, :path => "bootstrap/node.sh"
  end

end